var http = require("../../config/http.config");
var routers = require("../../config/routers.config");
var datastores = require("../../config/datastores.config");
var seeds = require("../../config/seeds.config");
var inputs = require("../../config/inputs.config");
module.exports.http = http;
module.exports.routers = routers;
module.exports.datastores = datastores;
module.exports.seeds = seeds;
module.exports.inputs= inputs
